### ISSUE TITLE
"No function given" lors de l'acquittement d'un message d'erreur

### ISSUE THREAD

**Issue by Feuilledethe** [franck-paul/errorlogger#11]
Bonjour

Quand le clique sur le bouton "Aknowledge" de la liste signalant des nouveaux enregistrements, j'ai ce message d'erreur lors de la demande d'acquittement d'un signalement et rien d'autre (perte de l'affichage de la partie admin et obligation de revenir en arrière ou de recharger une page normale) :

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<rsp status="failed">
<message>No function given</message>
</rsp>
```

Problème peut-être déjà présent sur les autres versions et, au passage, j'ai plusieurs lignes de signalement de nouveaux messages même quand il n'y en a qu'un.

```
Infos système
Version de PHP : 8.1.16
Gestionnaire de base de données : mysqli version 5.7.42 avec la syntaxe mysql
Niveau de rapport d'erreur PHP : 32759 = E_USER_DEPRECATED, E_DEPRECATED, E_RECOVERABLE_ERROR, E_STRICT, E_USER_NOTICE, E_USER_WARNING, E_USER_ERROR, E_COMPILE_WARNING, E_COMPILE_ERROR, E_CORE_WARNING, E_CORE_ERROR, E_PARSE, E_WARNING, E_ERROR
Cache PHP : Aucun
Dossier temporaire :/tmp
Infos Dotclear
Version de Dotclear : 2.26.0-p20230601.0829
Canal de mise à jour :testing
```

**Comment by Feuilledethe** [comment]
![Capture msg errorlogger 2023-06-02_01](https://github.com/franck-paul/errorlogger/assets/100703650/b207149c-ff59-48a9-974d-39304832f212)

**Comment by Feuilledethe** [comment]
Naturellement, maintenant que j'ai ouvert le ticket ... impossible de reproduire l'erreur.

**Comment by Feuilledethe** [comment]
Le problème s'est reproduit avec la mise à jour 2.26.0-p20230604.0913
J'ajoute qu'il n'y a aucune autre information sur la page affichée, c'est du simple html sans "l'habillage" Dotclear.

**Comment by franck-paul** [comment]
Un problème XML n'a rien à voir avec errorlogger puisqu'il n'utilise pas ce format et encore moins les fonctions REST qui l'utilisent (visiblement c'est un problème REST vu le message "No function given"). C'est donc un effet de bord d'un problème existant ailleurs.

**Comment by Feuilledethe** [comment]
Peut-être, mais à mon niveau, je vais avoir du mal à déterminer une origine possible surtout si elle est extérieure au plugin.

**Comment by franck-paul** [comment]
En attendant de pouvoir faire mieux, je ferme ce ticket qui n'a pas de rapport (que je sache à ce jour) avec ce plugin.
