### ISSUE TITLE
class ErrorLogger properties

### ISSUE THREAD

**Issue by nanart59** [franck-paul/errorlogger#3]
Je commence à scruter la classe ErrorLogger; dès la première methode __construct, je m'aperçois que :

- ligne 34 $this->loaded = false; <-> propriété n'est pas implémentée
- ligne 36 $this->old_error_handler <-> propriété implémentée de nom différent : old_errorhandler

apparemment anodin puisqu'aucune ne semble (ré)utilisée dans la classe elle-même

**Comment by franck-paul** [comment]
Je regarderai ça…
