### ISSUE TITLE
ErrorLogger permissions warning

### ISSUE THREAD

**Issue by Philippe-dev** [franck-paul/errorlogger#4]
J'ai régulièrement cette erreur sur mon installation locale, révélée par le plugin ErrorLogger :
2021-12-16 11:11:37	WARNING	.../dotclear/inc/libs/clearbricks/common/lib.files.php:324	chmod(): Operation not permitted	1	/dotclear/admin/services.php
Je ne sais pas si c'est un bug du plugin, ou plutôt une mauvaise config des permissions sur mes fichiers et si c'est le cas quelles seraient les permissions à appliquer ?
Pour info les permissions sur ce fichier, comme sur tous les autres sont (664) et (775) pour les répertoires

**Comment by Philippe-dev** [comment]
Il semble que ça ne soit pas une erreur de PHP, car l'erreur n'est pas dans les logs. C'est donc bien le plugin (en tout cas on dirait)

**Comment by franck-paul** [comment]
En fait ça ne concerne pas errorlogger qui se contente de capturer les erreurs PHP. Je ferme.
