### ISSUE TITLE
Fatal error on frontend when displaying errors in admin

### ISSUE THREAD

**Issue by franck-tomek** [franck-paul/errorlogger#5]
Stack trace: 
`PHP Fatal error:  Uncaught TypeError: dt::setTZ(): Argument #1 ($timezone) must be of type string, null given, called in /dc/inc/admin/lib.dc.notices.php on line 130 and defined in /dc/inc/helper/common/lib.date.php:380
Stack trace:
#0 /dc/inc/admin/lib.dc.notices.php(130): dt::setTZ(NULL)
#1 /dc/inc/admin/lib.dc.notices.php(138): dcAdminNotices::{closure}()
#2 /dc/inc/admin/lib.dc.page.php(337): dcAdminNotices::addNotice('warning', '<p>De nouvelles...', Array)
#3 /all-blogs/plugins/errorlogger/class.errorlogger.php(130): dcPage::addWarningNotice('<p>De nouvelles...', Array)
#4 /all-blogs/plugins/errorlogger/_prepend.php(20): ErrorLogger->setup()
#5 /dc/inc/core/class.dc.modules.php(1251): require('...')
#6 /dc/inc/core/class.dc.modules.php(478): dcModules->loadModuleFile('...')
#7 /dc/inc/public/class.dc.public.php(179): dcModules->loadModules('...', 'public', 'fr')
#8 /dc/inc/public/prepend.php(32): dcPublic->init()
#9 /blog/index.php(8): require('...')
#10 {main} thrown in /dc/inc/helper/common/lib.date.php on line 380`

DC 2.14.1, errorLogger 0.8

**Comment by franck-tomek** [comment]
Pour être plus précis, ça semble se produire quand on coche le mode perturbateur et qu'il y a une nouvelle erreur.

**Comment by franck-paul** [comment]
En fait c'est un bug côté Dotclear, corrigé avec ce commit : https://git.dotclear.org/dev/dotclear/commit/c17f678440258bb6b09ace0711a7101fe46bd9b9

**Comment by franck-tomek** [comment]
Vu, merci !
