### ISSUE TITLE
errorlogger pas content avec dc 2.25-dev-r20230204.0534

### ISSUE THREAD

**Issue by brol** [franck-paul/errorlogger#6]
coucou,

est-ce un pb avec errorlogger ou la dernière version ?
dans le doute, je poste ici.

dc 2.25-dev-r20230204.0534 sous wamp64

dès que je sélectionne un thème et clique sur utiliser celui-ci, j'ai ça (à noter que j'avais sélectionné noviny2 et non time-flies) : 
2023-02-04 19:11:23	WARNING	F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:28	Cannot declare class defaultWidgets, because the name is already in use	25	/blog_theme.php?shot=time-flies
Trace d'exécution

    [F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:28] : ::class_alias
    [F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:38] : dcProxyV2::classAliases
    [F:\wamp64\www\labodc2\dotclear\inc\core\class.dc.modules.php:1243] : ::require
    [F:\wamp64\www\labodc2\dotclear\inc\core\class.dc.modules.php:470] : dcModules::loadModuleFile
    [F:\wamp64\www\labodc2\dotclear\inc\admin\class.dc.admin.php:207] : dcModules::loadModules
    [F:\wamp64\www\labodc2\dotclear\inc\admin\prepend.php:23] : dcAdmin::init
    [F:\wamp64\www\labodc2\dotclear\admin\blog_theme.php:9] : ::require
    
quand je clique sur acquitter de error logger, ça me renvoie sur l'url d'un screenshot d'un thème installé mais même pas actif !

bref, super bizarre. j'ai du couper errorlogger car en plus il affecte le comportement côté public (par exemple la barre de menu de noviny ne s'affiche plus. si je désactive les logs d'erreurs de errorlogger et recharge la page côté public (ctrl F5), la barre revient). si tu as besoin de plus de précisions, je reste à dispo.

merci

**Comment by franck-paul** [comment]
Avec quelle version de errorlogger ? 0.8 ou 1.0 ?

À retester demain avec la nightly de cette nuit et la version 1.0 d'errorlogger et m'indiquer si c'est encore le cas.

**Comment by brol** [comment]
c'était avec 1.0, je te dis demain pour le reste.

**Comment by brol** [comment]
dc 2.25-dev-r20230204.1914

c'est encore le cas : 

2023-02-05 01:55:48 | WARNING | F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:28 | Cannot declare class dcWidget, because the name is already in use | 41 | /plugin.php?p=errorlogger

Trace d'exécution
[F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:28] : ::class_alias
[F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:38] : dcProxyV2::classAliases
[F:\wamp64\www\labodc2\dotclear\inc\core\class.dc.modules.php:1247] : ::require
[F:\wamp64\www\labodc2\dotclear\inc\core\class.dc.modules.php:485] : dcModules::loadModuleFile
[F:\wamp64\www\labodc2\dotclear\inc\admin\class.dc.admin.php:207] : dcModules::loadModules
[F:\wamp64\www\labodc2\dotclear\inc\admin\prepend.php:23] : dcAdmin::init
[F:\wamp64\www\labodc2\dotclear\admin\plugin.php:9] : ::require

traces d'exé identiques pour : 
2023-02-05 01:55:48 | WARNING | F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:28 | Cannot declare class dcWidgets, because the name is already in use | 41 | /plugin.php?p=errorlogger
et
2023-02-05 01:55:48 | WARNING | F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:28 | Cannot declare class defaultWidgets, because the name is already in use | 41 | /plugin.php?p=errorlogger

et quand je clique sur personnaliser le thème (noviny2), j'ai cette erreur en plus : 

2023-02-05 00:55:42 | WARNING | F:\wamp64\www\labodc2\dotclear\cache\cbtpl\aa\f4\aaf4689b02a3aa068d6ba2bafafa06ca.php:10 | Undefined array key "sql" | 1 | /

Trace d'exécution
[F:\wamp64\www\labodc2\dotclear\inc\helper\template\class.template.php:492] : ::include
[F:\wamp64\www\labodc2\dotclear\inc\public\class.dc.template.php:244] : template::getData
[F:\wamp64\www\labodc2\dotclear\cache\cbtpl\5b\ad\5bad8060abbd3335f32bfe6e624a4c87.php:36] : dcTemplate::getData
[F:\wamp64\www\labodc2\dotclear\inc\helper\template\class.template.php:492] : ::include
[F:\wamp64\www\labodc2\dotclear\inc\public\class.dc.template.php:244] : template::getData
[F:\wamp64\www\labodc2\dotclear\cache\cbtpl\02\c1\02c1bc687875fc61a77a917063ff80cc.php:311] : dcTemplate::getData
[F:\wamp64\www\labodc2\dotclear\inc\helper\template\class.template.php:492] : ::include
[F:\wamp64\www\labodc2\dotclear\inc\public\class.dc.template.php:244] : template::getData
[F:\wamp64\www\labodc2\dotclear\inc\public\lib.urlhandlers.php:173] : dcTemplate::getData
[F:\wamp64\www\labodc2\dotclear\inc\public\lib.urlhandlers.php:295] : dcUrlHandlers::serveDocument
[F:\wamp64\www\labodc2\dotclear\inc\helper\url.handler\class.url.handler.php:231] : dcUrlHandlers::home
[F:\wamp64\www\labodc2\dotclear\inc\helper\url.handler\class.url.handler.php:269] : urlHandler::callHelper
[F:\wamp64\www\labodc2\dotclear\inc\public\lib.urlhandlers.php:234] : urlHandler::callDefaultHandler
[F:\wamp64\www\labodc2\dotclear\inc\public\class.dc.public.php:265] : dcUrlHandlers::getDocument
[F:\wamp64\www\labodc2\dotclear\inc\public\prepend.php:32] : dcPublic::init
[F:\wamp64\www\labodc2\lab\index.php:3] : ::require

je te mets le fichier de cache (au format txt pour que ça soit accepté ici) en pj.
[5bad8060abbd3335f32bfe6e624a4c87.txt](https://github.com/franck-paul/errorlogger/files/10609992/5bad8060abbd3335f32bfe6e624a4c87.txt)

**Comment by franck-paul** [comment]
Une installation de growUp suivi d'un retour à l'accueil de l'admin pourrait aider.

Sinon vérifier qu'à la racine du plugin widgets il n'existe plus que le fichier PHP `_define.php`, les autres devraient avoir été supprimés et si ce n'est pas le cas les virer et refaire le test.

**Comment by brol** [comment]
j'ai installé growUp, puis retour à l'accueil. pas de changement. déconnexion de l'admin, reconnexion, pas de changement.
le dossier \dotclear\plugins\widgets comprend 4 dossiers et 10 fichiers au premier niveau. j'ai tout supprimé en ne laissant que le _define.php. et toujours des warnings (je continue à utiliser noviny2 (la barre de menu ne s'affiche toujours pas tant que errorlogger est activé)) : 

2023-02-05 16:11:14 | WARNING | F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:28 | Class "Dotclear\Plugin\widgets\Widgets" not found | 3 | /blog_theme.php?shot=time-flies

Trace d'exécution
[F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:28] : ::class_alias
[F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:38] : dcProxyV2::classAliases
[F:\wamp64\www\labodc2\dotclear\inc\core\class.dc.modules.php:1247] : ::require
[F:\wamp64\www\labodc2\dotclear\inc\core\class.dc.modules.php:485] : dcModules::loadModuleFile
[F:\wamp64\www\labodc2\dotclear\inc\admin\class.dc.admin.php:207] : dcModules::loadModules
[F:\wamp64\www\labodc2\dotclear\inc\admin\prepend.php:23] : dcAdmin::init
[F:\wamp64\www\labodc2\dotclear\admin\blog_theme.php:9] : ::require

traces d'exé identiques pour les suivants : 
2023-02-05 16:11:14 | WARNING | F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:28 | Class "Dotclear\Plugin\widgets\WidgetsElement" not found | 4 | /blog_theme.php?shot=brol

2023-02-05 16:11:14 | WARNING | F:\wamp64\www\labodc2\dotclear\plugins\dcProxyV2\_prepend.php:28 | Class "Dotclear\Plugin\widgets\WidgetsStack" not found | 4 | /blog_theme.php?shot=brol

je désactive errorlogger...

**Comment by brol** [comment]
et sinon, je fais comment pour configurer les widgets maintenant ? y a plus de menu...
merci

**Comment by brol** [comment]
ah ok, il ne faut virer que les fichiers php de premier niveau...

**Comment by brol** [comment]
en fait, dès que j'active errorlogger, la barre de menu et la sidebar disparaissent côté public, et j'ai des erreurs dans errorlogger. si je désactive (case à cocher "Activer les logs d'erreur"), tout retombe en marche.

**Comment by franck-paul** [comment]
C'est comment avec la dernière version 2.1.1 ?

**Comment by brol** [comment]
ça donne ça :

<table id="logs-list"><tr><th class="first nowrap">Date</th><th>Type</th><th>Fichier</th><th>Description</th><th>Compteur</th><th>URL</th></tr><tr class="line" id="p0"><td class="nowrap">2023-05-31 11:26:50</td><td>WARNING</td><td>F:\wamp64\www\labodc2\dotclear\cache\cbtpl\aa\f4\aaf4689b02a3aa068d6ba2bafafa06ca.php:18</td><td>Undefined array key &quot;sql&quot;</td><td>1</td><td>/</td></tr><tr id="pe0"><td colspan="6"><strong>Trace d'exécution</strong><ol><li>[F:\wamp64\www\labodc2\dotclear\src\Helper\Html\Template\Template.php:501] : ::include</li><li>[F:\wamp64\www\labodc2\dotclear\inc\public\class.dc.template.php:250] : Dotclear\Helper\Html\Template\Template::getData</li><li>[F:\wamp64\www\labodc2\dotclear\cache\cbtpl\5b\ad\5bad8060abbd3335f32bfe6e624a4c87.php:44] : dcTemplate::getData</li><li>[F:\wamp64\www\labodc2\dotclear\src\Helper\Html\Template\Template.php:501] : ::include</li><li>[F:\wamp64\www\labodc2\dotclear\inc\public\class.dc.template.php:250] : Dotclear\Helper\Html\Template\Template::getData</li><li>[F:\wamp64\www\labodc2\dotclear\cache\cbtpl\02\c1\02c1bc687875fc61a77a917063ff80cc.php:330] : dcTemplate::getData</li><li>[F:\wamp64\www\labodc2\dotclear\src\Helper\Html\Template\Template.php:501] : ::include</li><li>[F:\wamp64\www\labodc2\dotclear\inc\public\class.dc.template.php:250] : Dotclear\Helper\Html\Template\Template::getData</li><li>[F:\wamp64\www\labodc2\dotclear\inc\public\lib.urlhandlers.php:184] : dcTemplate::getData</li><li>[F:\wamp64\www\labodc2\dotclear\inc\public\lib.urlhandlers.php:306] : dcUrlHandlers::serveDocument</li><li>[N/A:N/A] : dcUrlHandlers::home</li><li>[F:\wamp64\www\labodc2\dotclear\src\Helper\Network\UrlHandler.php:237] : ::call_user_func</li><li>[F:\wamp64\www\labodc2\dotclear\src\Helper\Network\UrlHandler.php:279] : Dotclear\Helper\Network\UrlHandler::callHelper</li><li>[F:\wamp64\www\labodc2\dotclear\inc\public\lib.urlhandlers.php:245] : Dotclear\Helper\Network\UrlHandler::callDefaultHandler</li><li>[F:\wamp64\www\labodc2\dotclear\inc\public\class.dc.public.php:269] : dcUrlHandlers::getDocument</li><li>[F:\wamp64\www\labodc2\dotclear\inc\public\prepend.php:32] : dcPublic::init</li><li>[F:\wamp64\www\labodc2\lab\index.php:3] : ::require</li></ol></td></tr></table>

**Comment by brol** [comment]
[aaf4689b02a3aa068d6ba2bafafa06ca.txt](https://github.com/franck-paul/errorlogger/files/11612662/aaf4689b02a3aa068d6ba2bafafa06ca.txt)

**Comment by franck-paul** [comment]
Visiblement un plugin tiers qui joue avec les tags (meta), faudrait vider le cache template et retester.

C'est toujours en 2.25.x ?

**Comment by brol** [comment]
m'est avis que ça vient de arlequin 2.1, j'en cause avec JC.
non, j'ai fait la màj vers 2.27-dev-r20230529.0715 avant.

**Comment by franck-paul** [comment]
Ok, je ferme ici et on rouvrira si besoin
