### ISSUE TITLE
langue affichage menu erreurs

### ISSUE THREAD

**Issue by nanart59** [franck-paul/errorlogger#8]
Il semble que dans l'affichage du menu des erreurs les boutons restent en anglais

Some new error messages have been detected
[View error logs] [Acknowledge] [Don't bother me again]

errorlogger 2.0 dc2.6

**Comment by franck-paul** [comment]
Bizarre, je n'arrive pas à reproduire chez moi.

**Comment by nanart59** [comment]
Peut-être est-ce du au fait _(je viens de m'en apercevoir)_ que j'avais deux page admin sur le même blog (local) ouvertes en même temps ?
Tu peux fermer je reviendrais à la charge plus tard si le probleme se reproduit

**Comment by franck-paul** [comment]
Ok

**Comment by brol** [comment]
salut,
j'ai aussi le problème.
2.27-dev-r20230529.0715
php8.1.0 et 8.2.3
une seule page admin.

**Comment by franck-paul** [comment]
Merci de préciser le numéro de version où le problème se produit, je n'arrive pas à reproduire ni en prod, ni en dev

**Comment by brol** [comment]
errorlogger 2.2
