### ISSUE TITLE
Affichage des logs du plugin ErrorLogger quasi impossible (CSS ?)

### ISSUE THREAD

**Issue by Feuilledethe** [franck-paul/errorlogger#9]
Bonjour

Quand je visualise le journal du plugin ErrorLogger, il y a un gros problème d'affichage. Les icônes occupent toutes la largeur de l'écran et toute la partie information ou textuelle est repoussée loin en bas de page. Les symptômes ressemblent à un échec de prise en charge du CSS lors le l'affichage de la page dans la partie Administration. En comparant les fichiers présent sur mon serveur et ceux du dépôt git, je vois qu'il me manque le fichier dcstore.xml ; il n'a pas l'air d'avoir été téléchargé lors de la mise à jour du plugin entre les versions 1.0 2.1 et 2.1.1 . Je n'ai pas de message d'erreur et il n'y a pas d'impact côté public.

Le problème est corrigé en copiant le fichier dcstore.xml dans le répertoire du plugin.

ErrorLogger v2.1.1 (et précédentes)
DC 2.26 stable et 2.26.0-p20230521.1137 et 2.26.0-p20230523.1105 et 2.26.0-p20230529.0711

**Comment by franck-paul** [comment]
Le fichier dcstore.xml n'a pas à être distribué avec les plugins, il est seulement nécessaire dans les dépôts alternatifs pour indiquer la dernière version disponible.

Sur mon installation perso ce fichier n'est pas présent pour errorlogger et je n'ai pas ce problème d'icône que tu mentionnes.

Il serait intéressant pour essayer de reproduire le problème que tu indiques s'il y a des erreurs dans la console du navigateur, par exemple (échec de chargement d'une feuille de style, …)

**Comment by franck-paul** [comment]
Par ailleurs je suis assez curieux de savoir de quelles icônes tu parles vu que ce plugin n'en affiche pas dans son journal !

**Comment by Feuilledethe** [comment]
Ca casse complètement l'affichage côté administration, donc y compris les icônes Dotclear.

Pour complément d'information, Edge Version 112.0.1722.39

```
page-tabs.js:1  Uncaught ReferenceError: $ is not defined
    at jquery.pageTabs.js:1:20
    at jquery.pageTabs.js:9:346
page-tabs.js:1  Uncaught ReferenceError: $ is not defined
    at page-tabs.js:1:14
index.php?pf=errorlogger/js/admin.js:4  Uncaught ReferenceError: dotclear is not defined
    at index.php?pf=errorlogger/js/admin.js:4:1
```

![Capture web_30-5-2023_171054_memo feuilledethe fr](https://github.com/franck-paul/errorlogger/assets/100703650/f2eb6bce-b3a0-401f-a71a-1d19e717bb78)

**Comment by Feuilledethe** [comment]
et quand je réactive le fichier dcstore :

       ` GET http://memo.feuilledethe.fr/admin/plugin.php?p=errorlogger 500 (Internal Server Error)`

**Comment by franck-paul** [comment]
Alors dans ce cas désactive tous les plugins sauf errorlogger et dis-moi si le problème persiste

**Comment by Feuilledethe** [comment]
Le plugin présente toujours le même comportement, même quand c'est le seul plugin activé.

**Comment by franck-paul** [comment]
Quelle version de PHP ?

**Comment by Feuilledethe** [comment]
```
Infos système
Version de PHP : 8.1.16
Gestionnaire de base de données : mysqli version 5.7.42 avec la syntaxe mysql
Niveau de rapport d'erreur PHP : 32759 = E_USER_DEPRECATED, E_DEPRECATED, E_RECOVERABLE_ERROR, E_STRICT, E_USER_NOTICE, E_USER_WARNING, E_USER_ERROR, E_COMPILE_WARNING, E_COMPILE_ERROR, E_CORE_WARNING, E_CORE_ERROR, E_PARSE, E_WARNING, E_ERROR
Cache PHP : Aucun
Dossier temporaire :/tmp
Infos Dotclear
Version de Dotclear : 2.26.0-p20230529.0711
Version de Clearbricks : 2.0
Infos de mise à jour (depuis les versions en cache))
Canal : stable (2022-09-27T08:52:25+00:00)
Version : 2.23.1
URL de téléchargement : [https://download.dotclear.org/latest/dotclear-2.23.1.zip ](https://download.dotclear.org/latest/dotclear-2.23.1.zip)
Checksum :add0cf89d8545b1f09bc3c65ee9a7a8a
URL d'information : [https://services.dotclear.net/redir?about=dotclear-2.23.1 ](https://services.dotclear.net/redir?about=dotclear-2.23.1)
PHP min : 7.4
Canal : testing (2023-05-31T10:32:02+00:00)
Version : 2.26.0-p20230529.0711
URL de téléchargement : [https://download.dotclear.org/nightly/dotclear-2.26.0-p20230529.0711.zip ](https://download.dotclear.org/nightly/dotclear-2.26.0-p20230529.0711.zip)
Checksum :c3a23593e91c85d0b984eb96bb9ea0b7
URL d'information : [https://services.dotclear.net/redir?about=dotclear-testing ](https://services.dotclear.net/redir?about=dotclear-testing)
PHP min : 7.4
Attention : Oui
```

**Comment by Feuilledethe** [comment]
J'ai un autre message d'erreur qui n'a peut-être aucun rapport, mais qui me chiffonne dans le mesure où j'ai supprimé le plugin en question (Markdown syntax (formatting-markdown)) depuis plusieurs jours :

`
[Tue May 30 22:01:00 2023] [error] [client 114.119.155.36] ModSecurity: Access denied with code 403 (phase 2). Pattern match "\\b(\\d+) ?(?:=|<>|<=>|<|>|!=) ?\\1\\b|[\\'"\\`\\\xc2\xb4\\\xe2\x80\x99\\\xe2\x80\x98](\\d+)[\\'"\\`\\\xc2\xb4\\\xe2\x80\x99\\\xe2\x80\x98] ?(?:=|<>|<=>|<|>|!=) ?[\\'"\\`\\\xc2\xb4\\\xe2\x80\x99\\\xe2\x80\x98]\\2\\b|[\\'"\\`\\\xc2\xb4\\\xe2\x80\x98](\\w+)[\\'"\\`\\\xc2\xb4\\\xe2\x80\x99\\\xe2\x80\x98] ?(?:=|<>|<=>|<|>|!=) ?[\\'"\\`\\\xc2\xb4\\\xe2\x80\x99\\\xe2\x80\x98]\\3\\b|([\\'"\\;\\`\\\xc2\xb4\\\xe2\x80\x99\\\xe2\x80\x98]*)?\\s+(and|or)\\s+([\\s\\'"\\` ..." at REQUEST_FILENAME. [file "/usr/local/apache2/conf/modsecurity/base_rules/modsecurity_crs_41_sql_injection_attacks.conf"] [line "425"] [id "950901"] [rev "2.1.1"] [msg "SQL Injection Attack"] [data " and unordered lists"] [severity "CRITICAL"] [hostname "feuilledethe.fr"] [uri "/all-blogs/plugins/formatting-markdown/lib/test/resources/markdown.mdtest/Ordered and unordered lists.xhtml"] [unique_id "ZHZV-CS-kbDvfhseHA@r1QAAAKM"]`

**Comment by franck-paul** [comment]
Je viens d'ajouter une tâche de maintenance (plugin Entretien) qui permet de vider les logs d'errorlogger.

Faire la mise à jour (2.2), vider les caches avec le plugin Entretien et me dire si l'erreur persiste à la prochaine erreur enregistrée par errorlogger.

**Comment by Feuilledethe** [comment]
J'ai fait la mise à jour du plugin et vidé les caches (errorlooger et templates) et ça marche. J'ai retrouvé un affichage normal. Merci Pat'on

**Comment by franck-paul** [comment]
> J'ai un autre message d'erreur qui n'a peut-être aucun rapport, mais qui me chiffonne dans le mesure où j'ai supprimé le plugin en question (Markdown syntax (formatting-markdown)) depuis plusieurs jours :
> 
> `[Tue May 30 22:01:00 2023] [error] [client 114.119.155.36] ModSecurity: Access denied with code 403 (phase 2). Pattern match "\\b(\\d+) ?(?:=|<>|<=>|<|>|!=) ?\\1\\b|[\\'"\\`\\xc2\\xb4\\xe2\\x80\\x99\\xe2\\x80\\x98\](\\d+)\['"\`\\\\xc2\\xb4\\\\xe2\\x80\\x99\\\\xe2\\x80\\x98\] ?(?:=|\<>|\<=>|\<|>|!=) ?[\\'"\\`\\xc2\xb4\\xe2\x80\x99\\xe2\x80\x98]\2\b|[\'"\`\\\\xc2\\xb4\\\\xe2\\x80\\x98](%5Cw+)\[\\'"\\`\\xc2\xb4\\xe2\x80\x99\\xe2\x80\x98] ?(?:=|<>|<=>|<|>|!=) ?[\'"\`\\\\xc2\\xb4\\\\xe2\\x80\\x99\\\\xe2\\x80\\x98\]\\3\\b|(\[\\'"\\;\\`\\xc2\xb4\\xe2\x80\x99\\xe2\x80\x98]*)?\s+(and|or)\s+([\s\'"\` ..." at REQUEST\_FILENAME. \[file "/usr/local/apache2/conf/modsecurity/base\_rules/modsecurity\_crs\_41\_sql\_injection\_attacks.conf"\] \[line "425"\] \[id "950901"\] \[rev "2.1.1"\] \[msg "SQL Injection Attack"\] \[data " and unordered lists"\] \[severity "CRITICAL"\] \[hostname "feuilledethe.fr"\] \[uri "/all-blogs/plugins/formatting-markdown/lib/test/resources/markdown.mdtest/Ordered and unordered lists.xhtml"\] \[unique\_id "ZHZV-CS-kbDvfhseHA@r1QAAAKM"\]\`

Aucune idée d'où ça sort vu que c'est un fichier de test unitaire de la librairie utilisée dans le plugin, tests unitaires inopérant en production.

**Comment by Feuilledethe** [comment]
Pour ce dernier point, peut-être à mettre sur le dos d'un cache côté serveur qui ferait du zèle.
